package ca.bazlur.model;

public enum BookGenre {
    FICTION, NON_FICTION, MYSTERY, THRILLER, ROMANCE, SCIENCE_FICTION,
    FANTASY, BIOGRAPHY, HISTORY, SELF_HELP, BUSINESS, HEALTH,
    TRAVEL, COOKING, ART, POETRY, DRAMA, CHILDREN, YOUNG_ADULT
}
